services:
  # Base MongoDB pour note-service
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - medilabo-network
    volumes:
      - mongo_data:/data/db

  # Base MySQL pour patient-service
#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_DATABASE: patientsdb
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#
#    ports:
#      - "3308:3306"
#    networks:
#      - medilabo-network
#    volumes:
#      - mysql_data:/var/lib/mysql



  patient-service:
    build: ./patient-service
    container_name: patient-service
#    depends_on:
#      - mysql
    environment:
      # Force la datasource vers *medilabo* (passe devant application.properties)
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/patientsdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: medilabo
      SPRING_DATASOURCE_PASSWORD: medipass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 9001
    ports:
      - "9001:9001"
    networks:
      - medilabo-network


  note-service:
    build: ./note-service
    container_name: note-service
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/notedb
    ports:
      - "9002:9002"
    networks:
      - medilabo-network

  diabetes-risk-service:
    build: ./diabetes-risk-service
    container_name: diabetes-risk-service
    depends_on:
      - patient-service
      - note-service
    environment:
      SERVER_PORT: 9003
      PATIENT_SERVICE_URL: http://patient-service:9001
      NOTE_SERVICE_URL: http://note-service:9002
    ports:
      - "9003:9003"
    networks:
      - medilabo-network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    depends_on:
      - patient-service
      - diabetes-risk-service
    environment:
      SERVER_PORT: 8080
      PATIENT_SERVICE_URL: http://patient-service:9001
      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: patient-service
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://patient-service:9001
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/api/patients,/api/patients/**
      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: front-service
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://front-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: Path=/login,/css/**,/js/**,/images/**,/assets/**

    ports:
      - "8080:8080"
    networks:
      - medilabo-network

  front-service:
    build: ./front-service
    container_name: front-service
    depends_on:
      - patient-service
      - note-service
      - diabetes-risk-service
    environment:
      # Spring Boot fait le mapping ENV -> propriétés (SERVER_PORT -> server.port, etc.)
      SERVER_PORT: 8081
      PATIENT_SERVICE_URL: http://patient-service:9001
      NOTE_SERVICE_URL: http://note-service:9002
      RISK_SERVICE_URL: http://diabetes-risk-service:9003
    ports:
      - "8081:8081"
    networks:
      - medilabo-network


networks:
  medilabo-network:
   driver: bridge

volumes:
  mongo_data:
  mysql_data:
