spring.application.name=gateway-service
server.port=8080
# Activer tous les endpoints actuator
management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true

# Configuration des routes vers patient-service
spring.cloud.gateway.routes[0].id=patient-service
spring.cloud.gateway.routes[0].uri=http://localhost:9001
spring.cloud.gateway.routes[0].predicates[0]=Path=/patient/**
