spring.application.name=front-service
server.port=8081

patient.service.url=http://patient-service:9001
note.service.url=http://note-service:9002
risk.service.url=http://localhost:9003
logging.level.root=info
spring.thymeleaf.cache=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
