#spring.application.name=front-service
#server.port=8081
#
#patient.service.url=http://localhost:9001
#note.service.url=http://localhost:9002
#
#logging.level.root=info
#
#management.endpoints.web.exposure.include=health
#management.endpoint.health.show-details=always

spring.application.name=front-service
server.port=8081

patient.service.url=http://patient-service:9001
note.service.url=http://note-service:9002

logging.level.root=info

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
