spring.application.name=front-service
server.port=8081

patient.service.url=http://patient-service:9001
note.service.url=http://note-service:9002
risk.service.url=http://localhost:9003
logging.level.root=info
spring.thymeleaf.cache=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# afficher messages/stacktraces sur la page d?erreur
server.error.include-message=ALWAYS
server.error.include-stacktrace=ALWAYS

# logs plus verbeux utiles pour 404/templating
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.PageNotFound=DEBUG
logging.level.org.thymeleaf=DEBUG
